spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/voting-system?authSource=admin
      database: voting-system
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration